### ISSUE TITLE
Update to v1.2.3

### ISSUE THREAD

**Issue by ajgringo619** [flathub/org.x.Warpinator#3]
Do you have a time-frame on if/when this will happen? Looking forward to testing the new network selection with my VMware subnet.

**Comment by K0-RR** [comment]
Seems like the app dev made the required changes so can the flathub team update it to 1.2.4?

**Comment by mtwebster** [comment]
I'll take a look, it shouldn't take this long, could be an issue with the build.

**Comment by mtwebster** [comment]
updated.
